name: Generate Changelog
on:
  push:
    branches:
      - main # Change this to your repository's default branch

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install

      - name: Generate Changelog
        run: npx standard-version
